spring:
  application:
    name: troops #change this

  datasource:
    url: jdbc:postgresql://localhost:5418/troops_db
    username: acc_dev
    password: acc_dev12

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  docker:
    compose:
      enabled: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  address: 0.0.0.0
  port: 8080